### ISSUE TITLE
Do not start timer until after 2 participants are connected.

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#43]
2018-11-27 00:46:49.293 [INF] DCMIX: Zero participant connected
2018-11-27 00:46:49.295 [INF] DCMIX: Will start next join session at 00:48:49

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/12a6ee3b6551e3ad7521d87ec745e3c041f74110

**Comment by raedah** [comment]
Still seeing this

2018-12-04 07:43:46.953 [INF] DCMIX: Will start next join session at 07:45:46
2018-12-04 07:45:46.963 [INF] DCMIX: Will start next join session at 07:47:46
2018-12-04 07:47:46.952 [INF] DCMIX: Will start next join session at 07:49:46
2018-12-04 07:49:46.962 [INF] DCMIX: Will start next join session at 07:51:46

**Comment by huyntsgs** [comment]
Refixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/c4727ee119474a7fa90883727c4dbce05d801d49
